feat(ui): HomePage
mission-apprentissage/flux-retour-cfas pull request #1758
Opened 2022-09-12 09:02 UTC by pabloHry

Creation de la homepage

Figma : **https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=5054%3A115864**

2022-09-12 09:31 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +      <Section withShadow paddingY="4w" color="#000000" background="#F6F6F6">
On a pas les couleurs dans le theme ? 🤔

2022-09-12 09:31 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +                Le service public pour visualiser en <strong>temps réel</strong> les effectifs d’apprentis dans les
Dans la maquette j'ai la phrase "Service public pour ..." et pas de "Le" devant

2022-09-12 09:36 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +              width="50%"
Pourquoi Width à 50% 
Il me semble qu'il y a un espace entre les 2 box donc on peut laisser l'espace

2022-09-12 16:36 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +                Le service public pour visualiser en <strong>temps réel</strong> les effectifs d’apprentis dans les
Dans la maquette la phrase c'est "les effectifs d'apprentis en temps réel"

2022-09-12 16:37 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +                politique de l’apprentissage nationalement et dans les territoires.
politique de l'apprentissage en gras dans la maquette

2022-09-12 16:37 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +                  Consulter les données
Dans le figma c'est marqué : "Se connecter" à la place de consulter les données

2022-09-12 16:38 UTC, sbenfares requested changes
Des écarts avec ce que j'ai vu dans la maquette, faire le point avec @ClemLan ou @cathbaiona

2022-09-13 18:01 UTC, sbenfares approved these changes

2022-09-15 07:13 UTC, sbenfares requested changes
Je valide pas encore car il manque le reste

2022-09-22 09:29 UTC, sbenfares commented on server/src/http/routes/healthcheck.route.js
> +        redisPort: config.redis.uri,
tu peux la supprimer stp ?

2022-09-22 09:29 UTC, sbenfares commented on ui/src/common/components/BaseAccordionGroup/BaseAccordionGroup.js
> +  console.log(isHomePage);
a supprimer

2022-09-22 09:29 UTC, sbenfares commented on ui/src/common/components/BaseAccordionGroup/BaseAccordionGroup.js
> +      {isHomePage && (
isHomePage === true plutot non ?

2022-09-22 09:30 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +              to={"/organisme-formation"}
à la place de "/organisme-formation" tu peux mettre la constante dans NAVIGATION_PAGES stp ?

2022-09-22 09:48 UTC, sbenfares requested changes
Il faut revoir l'affichage de l'apercu des données au national.

Cf. maquette 👇🏼 
![image](https://user-images.githubusercontent.com/18660099/191715678-bd19ae79-2772-4db7-ba84-b83ea687c4ce.png)

2022-09-22 09:49 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +      <Section paddingY="8w" color="grey.800">
paddingY="8w" c'est pas un peu trop par rapport à la maquette ?

2022-09-22 09:49 UTC, sbenfares commented on ui/src/pages/home/sections/VosDonneesNourrissentLeTableauDeBord.js
> +    <Section paddingY="8w" color="grey.800">
paddingY="8w" too much

2022-09-22 09:51 UTC, sbenfares commented on ui/src/pages/home/sections/VosDonneesNourrissentLeTableauDeBord.js
> +        </Box>
Le hover la dessus est un peu "moche", c'est le cas sur tous les liens soulignés d'ailleurs.
Jte laisse checker si tu peux faire un truc plus propre ;)

2022-09-22 09:51 UTC, sbenfares commented on ui/src/pages/home/sections/VosDonneesNourrissentLeTableauDeBord.js
> +        <Box flex="1" marginLeft="8w">
Il manque pas un picto entre les 2 colonnes ? 

![image](https://user-images.githubusercontent.com/18660099/191716472-b10cc980-66c2-458a-8cd3-67e39628a51c.png)

2022-09-22 09:53 UTC, sbenfares commented on ui/src/pages/home/sections/ameliorer-les-pratiques/AmeliorerLesPratiques.js
> +          Vous souhaitez contribuer à l’évolution du {PRODUCT_NAME} ?
Dans la maquette le texte n'est pas en gras et me semble plus petit

2022-09-22 09:54 UTC, sbenfares commented on ui/src/pages/home/HomePage.js
> +        <Heading as="h1"> Une question ? </Heading>
Dans la maquette le wording est "Des questions ?"

2022-09-22 09:55 UTC, sbenfares commented on ui/src/common/components/BaseAccordionGroup/BaseAccordionGroup.js
> +          Voir davantage de questions
Attention au spacing je trouve que c'est trop collé par rapport à la maquette : 

![image](https://user-images.githubusercontent.com/18660099/191717198-e3b63658-001d-49d1-a0d9-125219d3ce71.png)


vs 

![image](https://user-images.githubusercontent.com/18660099/191717241-87864a21-d1e2-4c2c-8475-cddc205c2295.png)

2022-09-22 10:03 UTC, cathbaiona commented on ui/src/pages/home/sections/VosDonneesNourrissentLeTableauDeBord.js
> +        <Box flex="1" marginLeft="8w">
J'ai viré l'icône . il s'agit d'une erreur

2022-09-22 10:07 UTC, sbenfares commented on ui/src/pages/home/sections/VosDonneesNourrissentLeTableauDeBord.js
> +        <Box flex="1" marginLeft="8w">
@pabloHry ne pas prendre en compte ma remarque alors ;)
@cathbaiona je vous laisse supprimer dans Figma aussi avec @ClemLan ? 🙏🏼

2022-09-26 13:16 UTC, pabloHry commented on ui/src/common/components/BaseAccordionGroup/BaseAccordionGroup.js
> +      {isHomePage && (
isHomePage est un Boolean pas besoins de mettre === true

2022-09-27 09:17 UTC, sbenfares commented
Il te reste qqs remarques à traiter + pense à rebase  

- https://github.com/mission-apprentissage/flux-retour-cfas/pull/1758/files#r977423928
- https://github.com/mission-apprentissage/flux-retour-cfas/pull/1758/files#r977450148
- https://github.com/mission-apprentissage/flux-retour-cfas/pull/1758/files#r977425363
- https://github.com/mission-apprentissage/flux-retour-cfas/pull/1758/files#r977446078

2022-09-27 12:42 UTC, sbenfares commented on ui/src/common/components/BaseAccordionGroup/BaseAccordionGroup.js
> +          Voir davantage de questions
@pabloHry j'ai oublié, tu peux virer le lien **to="/questions-reponses"** et mettre la constante de NavigationsPages stp ?

Merci

2022-10-17 13:03 UTC, closed without merging