Modification HomePage
mission-apprentissage/flux-retour-cfas pull request #2071
Opened 2022-10-19 21:12 UTC by pabloHry

2022-10-20 05:25 UTC, antoinebigard reviewed
Elle est où l'issue rattachée à cette pr stp ?

2022-10-20 05:25 UTC, antoinebigard commented on ui/src/common/constants/product.js
> +export const PRODUCT_NAME = "tableau de bord de l'apprentissage";
tu es sur de toi ? c'est absolument partout qu'il faut changer le nom ? 42 référemces

2022-10-20 07:31 UTC, pabloHry commented on ui/src/common/constants/product.js
> +export const PRODUCT_NAME = "tableau de bord de l'apprentissage";
https://docs.google.com/presentation/d/1_bjiwlag_Z5n4u6UYsdkVkmfL2DNaq6dCGs1G3u1X4o/edit#slide=id.p

2022-10-28 13:48 UTC, sbenfares commented on ui/src/pages/home/sections/ameliorer-les-pratiques/AmeliorerLesPratiques.js
> +          besoins
```suggestion
          besoins.
```

2022-10-28 13:49 UTC, sbenfares requested changes
D'après les demandes faites ici https://docs.google.com/presentation/d/1_bjiwlag_Z5n4u6UYsdkVkmfL2DNaq6dCGs1G3u1X4o/edit#slide=id.g16e7a2432a8_0_16

Il manque pour moi  remplacer "Qu'est-ce que le Tableau de bord" par A quoi sert le tableau de  bord ?

2022-11-02 15:31 UTC, merged