feat: import du reseau aden
mission-apprentissage/flux-retour-cfas pull request #2401
Opened 2023-01-17 07:43 UTC by svengau

ajout du reseau Aden

2023-01-17 08:52 UTC, sbenfares commented on server/src/common/constants/networksConstants.js
>    CMA: {
Tu peux le supprimer, pas utile.

2023-01-17 08:54 UTC, sbenfares requested changes
OK pour moi, penser juste à supprimer l'entrée dans RESEAUX_CFAS inutile (et qui risque peut-être de faire planter l'ancien job si on a besoin de le lancer) + faire un rebase de develop pour être à jour :)

2023-01-17 09:37 UTC, svengau commented on server/src/common/constants/networksConstants.js
>    CMA: {
si je supprime, impossible d'importer

2023-01-17 10:33 UTC, antoinebigard commented on server/src/common/constants/networksConstants.js
>    CMA: {
Attention RESEAUX_CFAS est dans l'enum !

2023-01-17 10:36 UTC, svengau commented on server/src/common/constants/networksConstants.js
>    CMA: {
discuté avec @sbenfares et ok pour lui

2023-01-17 10:44 UTC, sbenfares approved these changes
Merci @svengau

2023-01-17 11:26 UTC, merged

2023-01-17 11:26 UTC, antoinebigard commented
:tada: This PR is included in version 3.2.0-beta.1 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/flux-retour-cfas/releases/tag/v3.2.0-beta.1)
- `v3.2.0-beta.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-18 17:08 UTC, antoinebigard commented
:tada: This PR is included in version 3.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/flux-retour-cfas/releases/tag/v3.2.0)
- `v3.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: