chore(server): remplacement de la route /siret-uai-reseaux par /organismes pour conso par réferentiel
mission-apprentissage/flux-retour-cfas pull request #2447
Opened 2023-01-24 07:14 UTC by sbenfares

Remplacement de la route /siret-uai-reseaux par une route /organismes avec les informations du stock des organismes, sera appelée par le référentiel

2023-01-24 07:20 UTC, antoinebigard commented on server/src/http/server.js
> +
Il faudrait mettre une API key

2023-01-24 07:33 UTC, sbenfares commented on server/src/http/server.js
> +
Ok

2023-01-24 07:35 UTC, svengau approved these changes
juste quelques remarques non bloquantes

2023-01-24 07:35 UTC, svengau commented on server/src/http/routes/specific.routes/old/referentiel.route.js
> -    "/siret-uai-reseaux",
au cas ou: est-ce qu'il y a besoin de garder la route et mettre un redirect ?

2023-01-24 07:35 UTC, svengau commented on server/src/http/routes/specific.routes/organismes.routes.js
> +        limit: Joi.number(),
ca serait pas mal de rajouter min et max

2023-01-24 07:35 UTC, svengau commented on server/src/http/routes/specific.routes/organismes.routes.js
> +        organismes: omittedData,
On pourrait peut etre normer tous les retour, en mettant par exemple les données retournées dans result ou data ?

2023-01-24 07:37 UTC, sbenfares commented on server/src/http/routes/specific.routes/old/referentiel.route.js
> -    "/siret-uai-reseaux",
🤔 je dirais non car c'est moi qui fera la PR pour changer la route de l'autre coté (coté référentiel)

2023-01-24 07:40 UTC, sbenfares commented on server/src/http/routes/specific.routes/organismes.routes.js
> +        organismes: omittedData,
pkoi pas, on se créé une carte dans le kanban pour checker tous les retour ? (préférence pour data de mon coté)

2023-01-24 07:48 UTC, sbenfares commented on server/src/http/routes/specific.routes/organismes.routes.js
> +        limit: Joi.number(),
Idem je propose qu'on fasse une carte "normalisation" des retours paginés ou on mettrait ça partout ou nécessaire

2023-01-24 07:57 UTC, antoinebigard commented on server/src/http/routes/specific.routes/organismes.routes.js
> +        organismes: omittedData,
dans l'idée "à discuter "  mais un gros ⚠️  attention à ne pas alourdir les projets ! le but est de sortir de la feature => création de valeur métier! Ne pas créer de friction par des normes et regles trop lourde sur les projets. Exemple si fast feature ne pas perdre du temps sur "Hey il faut suivre tel ou tel regles un peu custom"

2023-01-24 08:26 UTC, svengau commented on server/src/http/routes/specific.routes/organismes.routes.js
> +        organismes: omittedData,
je comprends l'approche, en meme temps, faut relativiser, c juste un champs à renommer. De la meme maniere qu'on utilise `pagination` partout, et pas `paginationOrganisme` ^_^

2023-01-24 09:57 UTC, sbenfares commented on server/src/http/server.js
> +
Re @antoinebigard du coup je propose : 

- Ajout d'un middleware header api key
- Ajout d'une variable apiKey organsimes (nom à trouver)
- Protection de la route via cette api key
- Coté référentiel, ajout de l'API Key en variable et update de l'appel api TDB

👉🏼 juste coté infra référentiel tu sais si j'aurais la main pour déployer ou je dois voir avec l'Onisep ?

2023-01-25 07:34 UTC, svengau approved these changes

2023-01-25 08:13 UTC, antoinebigard requested changes

2023-01-25 08:13 UTC, antoinebigard commented on server/src/http/middlewares/requireApiKeyAuthentication.js
> +};
le passport-localapikey c'est de l'historique le package.json 
Je prefererai qu'on part sur qqch de plus standard oAuth avec un Bearer classique 
https://www.npmjs.com/package/passport-http-bearer

2023-01-30 09:31 UTC, sbenfares commented
Vu ensemble si ok pour vous @antoinebigard @svengau on reste sur l'API Key via passport-localapikey pour le moment ?

2023-01-30 15:44 UTC, merged