Fix/create admin user
mission-apprentissage/flux-retour-cfas pull request #2507
Opened 2023-02-03 18:05 UTC by totakoko

Encore basé sur #2505. Je refais un rebase après merge.

Tentative pour corriger les permissions d'un administrateur nouvellement créé depuis l'UI.
Contrairement à un admin créé depuis la CLI, l'UI n'ajoute pas les permissions automatiquement.

Les changements :
- le champ `is_cross_organismes` est mis à true si `is_admin`, car non envoyé depuis l'UI (j'avais cru voir une checkbox côté UI mercredi donc soit elle a été supprimée, soit j'ai louché :stuck_out_tongue_closed_eyes: ) 
- le champ `account_status` passe à `FORCE_RESET_PASSWORD` pour ne pas obliger l'utilisateur à renseigner d'autres infos à la connexion. Infos sur son organisme (qu'il n'a pas) si j'ai bien compris.
- la fonctione `userAfterCreate()` est appelée pour créer des permissions. Ici une seule entrée dans la collection permissions.

Avec cette PR, un administrateur créé peut accéder à la partie administration, mais je n'ai pas fait d'autres tests.

Voici un petit état des lieux de l'appel des fonctions `createUser` et `userAfterCreate`.
En vert, l'appel qui a été ajouté.
Est-ce qu'il faudrait appeler `userAfterCreate` après chaque appel à `createUser` ?

![image](https://user-images.githubusercontent.com/8938024/216675008-ea6e3b45-3203-49f5-b487-e711bf5196d3.png)

2023-02-09 07:26 UTC, svengau requested changes
il faut aussi gerer le cas ou on met a jour un profil utilisateur (pour "fixer" les comptes créees la semaine derniere pendant l'onboarding). Je pense que ca a du sens de le mettre dans cette PR, mais comme tu le sens.

2023-02-09 07:46 UTC, sbenfares commented
+1 pour l'update.
Est-ce qu'on rajouterais pas des tests unitaires sur la route ?

2023-02-09 11:18 UTC, totakoko commented
Suite à mon message dans Slack et après discussion avec Sven, je suis parti pour ne plus utiliser la méthode `userAfterCreate` car elle ne fonctionne pas vraiment pour les cas non admin...

Donc j'ai modifié le code pour ne créer une entrée dans permissions que pour un admin.
J'ai également ajouté une migration de données pour compléter les permissions manquantes pour les admins et définir is_cross_organismes à true quand admin.

Cela veut dire qu'à la création d'un utilisateur :
- admin => is_admin = true, is_cross_organismes = true + entrée dans permission avec organisme.admin
- non admin => is_admin = false, is_cross_organismes = false

À la mise à jour de la coche admin : changement de is_admin et is_cross_organismes, RIEN dans la table permission (faut-il changer ça ?)

@sbenfares @svengau Des avis ? :hugs:

2023-02-09 15:39 UTC, totakoko commented
- Mise à jour pour ne plus mettre à jour is_cross_organismes sauf à la création d'un admin.
- La permission organisme.admin est maintenant synchronisée (ajouté/supprimée avec le flag is_admin)

2023-02-10 07:22 UTC, svengau requested changes
désolé, mais ca marche toujours pas. J'ai crée un user, updaté pour lui donner les droits d'admin, et avec ce user, je n'arrive pas a afficher la liste des organismes. j'ai une 401 sur http://localhost/api/indicateurs

2023-02-10 09:36 UTC, totakoko commented
@svengau C'est corrigé.

2023-02-10 09:43 UTC, svengau approved these changes

2023-02-10 09:44 UTC, merged

2023-02-13 15:15 UTC, antoinebigard commented
:tada: This PR is included in version 3.8.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/flux-retour-cfas/releases/tag/v3.8.0)
- `v3.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: