chore(server): suppression cfas route inutilisée
mission-apprentissage/flux-retour-cfas pull request #2589
Opened 2023-02-14 13:45 UTC by sbenfares

2023-02-14 13:54 UTC, svengau requested changes

2023-02-14 13:54 UTC, svengau commented on ui/common/api/tableauDeBord.js
> -export const fetchSearchCfas = async (filters) => {
ya encore des occurrences dnas le code

2023-02-14 14:35 UTC, sbenfares commented on ui/common/api/tableauDeBord.js
> -export const fetchSearchCfas = async (filters) => {
Ah oui je regarde merci

2023-02-23 09:55 UTC, sbenfares commented
Fermeture car doublon avec la PR : https://github.com/mission-apprentissage/flux-retour-cfas/pull/2615

2023-02-23 09:55 UTC, closed without merging