chore(server): ajout d'une règle de fiabilisation pour les organismes inexistants
mission-apprentissage/flux-retour-cfas pull request #2952
Opened 2023-04-20 14:54 UTC by sbenfares

Utilisation de la collection UAIs ACCE du référentiel de manière identique que ce que l'on fait avec la collection organismes du référentiel. D'ou l'update du script hydrate:organismes-referentiel

Ajout d'une règle coté fiab pour checker si un organisme n'a pas son UAI dans ACCE (via cette collection) et n'a pas son siret dans les organismes du référentiel alors on considère qu'il est inexistant (traitement spécifique coté métier)

2023-04-21 04:23 UTC, svengau requested changes
qq comments a discuter ensemble.

2023-04-21 04:23 UTC, svengau commented on server/src/common/model/uaisAcceReferentiel.model.ts
> +const collectionName = "uaisAcceReferentiel";
stp, peux tu ajouter une petite pour expliquer ACCE, la difference avec OrganismeReferentiel, et comment on l'utilise ? merci

D'ailleurs, ca pourrait aussi etre dnas un markdown dédié ou on explique toutes les sources de données et leur usage

2023-04-21 04:23 UTC, svengau commented on server/src/common/model/uaisAcceReferentiel.model.ts
> +const indexes: [IndexSpecification, CreateIndexesOptions][] = [[{ uai: 1 }, {}]];
pas de clé d'unicité ?

2023-04-21 04:23 UTC, svengau commented on server/src/jobs/hydrate/organismes/hydrate-organismes-referentiel.ts
> +    await uaisAccesReferentielDb().insertOne({ uai } as UaisAcceReferentiel);
peut etre updateOne with upsert pour gerer les doublons ?

2023-04-21 04:23 UTC, svengau commented on server/src/jobs/hydrate/organismes/hydrate-organismes-referentiel.ts
> +    await createJobEvent({
ce job tourne tous les jours, et ya 33_367 uais. Du coup j'ai peur que cela soit le genre de mecanisme qui nous joue des tours.
Pourquoi ne pas logguer un log d'erreurs plutot, et si nbUaiAcceNotCreated > 0, et envoyer une alerte slack ou sentry pour qu'on regarde ? Grafana a aussi un systeme d'alerting. cc @totakoko

2023-04-21 04:23 UTC, svengau commented on server/src/common/apis/apiReferentielMna.ts
> +  const { data } = await axiosClient.get("/uais", {
le endpoint n'est pas dans la doc d'API. Besoin de la mettre a jour ?

2023-04-21 08:39 UTC, sbenfares commented on server/src/common/model/uaisAcceReferentiel.model.ts
> +const collectionName = "uaisAcceReferentiel";
Bonne remarque, j'ai commencé un petit fichier 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2952/commits/9cf921392654e5201ffb1c5e11e1f9ec230767ed

2023-04-21 08:40 UTC, sbenfares commented on server/src/common/model/uaisAcceReferentiel.model.ts
> +const indexes: [IndexSpecification, CreateIndexesOptions][] = [[{ uai: 1 }, {}]];
C'est un oubli, bien vu ! 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2952/commits/6ef010ef6cc29544b16597a7bdf50720aeaca442

2023-04-21 08:55 UTC, sbenfares commented on server/src/common/apis/apiReferentielMna.ts
> +  const { data } = await axiosClient.get("/uais", {
Il s'agit de l'API du référentiel par de la notre.

2023-04-21 08:59 UTC, sbenfares commented on server/src/jobs/hydrate/organismes/hydrate-organismes-referentiel.ts
> +    await createJobEvent({
Effectivement, c'est même applicable à d'autres traitements.
On pourrait repenser la gestion d'erreurs et définir celles qui nécessitent un alerting particulier

2023-04-24 13:57 UTC, totakoko approved these changes

2023-04-24 13:59 UTC, merged

2023-04-27 06:58 UTC, antoinebigard commented
:tada: This PR is included in version 3.22.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/flux-retour-cfas/releases/tag/v3.22.0)
- `v3.22.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: