chore(server): tests using cross-env
mission-apprentissage/flux-retour-cfas pull request #2998
Opened 2023-05-10 09:24 UTC by sbenfares

2023-05-10 10:26 UTC, svengau requested changes
il y a deja `dotenv.config({ path: "./.env.test" });` dans setupFiles.ts

2023-05-10 10:34 UTC, sbenfares commented
> il y a deja `dotenv.config({ path: "./.env.test" });` dans setupFiles.ts

Il s'agit de cross-env et pas dotenv, étant sous windows (:trollface:) c'est pour me permettre de lancer des scripts avec le set des variables d'environnement.
 
👉🏼 https://github.com/kentcdodds/cross-env

2023-05-10 14:22 UTC, svengau approved these changes

2023-05-10 14:24 UTC, merged

2023-05-12 04:19 UTC, antoinebigard commented
:tada: This PR is included in version 3.26.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/flux-retour-cfas/releases/tag/v3.26.0)
- `v3.26.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: