fix: mise à jour des organismes pour réparer l'encart admin et le paramétrage quand il est déjà fait
mission-apprentissage/flux-retour-cfas pull request #3421
Opened 2023-12-11 16:06 UTC by rap2hpoutre

2023-12-11 16:29 UTC, sbenfares requested changes

2023-12-11 16:29 UTC, sbenfares commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +        mode_de_transmission_configuration_author_fullname: "rap2h",
Alors avec tout le respect que j'ai pour ton travail, je me demande si on ne mettrait pas un truc du genre "MIGRATION" ou autre pour identifié qu'ils ont bien été paramétrés par migration.

2023-12-11 16:29 UTC, sbenfares commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +      api_key: { $ne: "" },
⚠️ 🤔  je me demande s'il ne faudrait pas plutôt :  **{ $exists : true** } car sinon on risque de modifier les cas ou l'on a pas le champ en base du tout.

2023-12-12 08:06 UTC, rap2hpoutre commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +        mode_de_transmission_configuration_author_fullname: "rap2h",
:D

2023-12-12 08:07 UTC, rap2hpoutre commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +      api_key: { $ne: "" },
```suggestion
      api_key: { $exists : true },
```

2023-12-12 08:07 UTC, rap2hpoutre commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +        mode_de_transmission_configuration_author_fullname: "rap2h",
```suggestion
        mode_de_transmission_configuration_author_fullname: "migration 2023-12",
```

2023-12-12 09:07 UTC, sbenfares requested changes

2023-12-12 09:07 UTC, sbenfares commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +      mode_de_transmission: { $exists: false },
Alors en lançant la migration chez moi je me demande si le **mode_de_transmission: { $exists: false },** ne va pas nous faire oublier des cas. 

Je trouve des organismes avec une API_KEY et mode_de_transmission = "API" mais n'ayant pas les autres champs donc je serais pour supprimer cette condition et tester.

2023-12-12 09:15 UTC, rap2hpoutre commented on server/src/db/migrations/20231211152119-mode_de_transmission.ts
> +      mode_de_transmission: { $exists: false },
OK merci je fais ça !

2023-12-12 10:04 UTC, rap2hpoutre commented
Normalement c'est bon 🤞

2023-12-12 10:35 UTC, sbenfares approved these changes

2023-12-12 10:56 UTC, merged