feat: ajout de la page Indicateurs nationaux
mission-apprentissage/flux-retour-cfas pull request #3470
Opened 2024-01-05 20:56 UTC by moroine

https://tableaudebord-apprentissage.atlassian.net/browse/TM-627

2024-01-05 20:58 UTC, moroine commented
🚀

2024-01-05 21:43 UTC, moroine commented
🚀

2024-01-09 14:08 UTC, rap2hpoutre requested changes
J'ai des erreurs ici : 

<img width="849" alt="Capture d’écran 2024-01-09 à 15 08 19" src="https://github.com/mission-apprentissage/flux-retour-cfas/assets/1575946/ec299ec7-87ac-4f17-92be-62315e7cc566">

```
{
  "name": "Flux Retour Cfas",
  "hostname": "x",
  "pid": 3666,
  "level": 50,
  "type": "http",
  "responseTime": 5,
  "method": "GET",
  "url": "/api/v1/indicateurs/national",
  "statusCode": 500,
  "error": {
    "isBoom": true,
    "isServer": true,
    "data": null,
    "output": {
      "statusCode": 500,
      "payload": {
        "statusCode": 500,
        "error": "Internal Server Error",
        "message": "An internal server error occurred"
      },
      "headers": {}
    },
    "message": "Object.keys(...).toSorted is not a function",
    "stack": "TypeError: Object.keys(...).toSorted is not a function\n    at getIndicateursNational (file:///..../flux-retour-cfas/server/dist/main-WLCF6FPG.js:1574:41)\n    at file:///..../flux-retour-cfas/server/dist/main-WLCF6FPG.js:3454:20\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///..../flux-retour-cfas/server/dist/main-WLCF6FPG.js:2406:20"
  },
  "msg": "request errored",
  "time": "2024-01-09T14:07:04.548Z",
  "v": 0
}
```

2024-01-09 15:26 UTC, rap2hpoutre approved these changes
Ah c'est bon ça marche !!

2024-01-09 15:35 UTC, merged