feat: ajout du conputed formation des effectifs depuis formation catalogue
mission-apprentissage/flux-retour-cfas pull request #3864
Opened 2024-10-18 13:23 UTC by nkrmr

Cf: [TM-1629](https://tableaudebord-apprentissage.atlassian.net/browse/TM-1629)

2024-10-21 14:18 UTC, sbenfares approved these changes

2024-10-24 08:39 UTC, moroine requested changes

2024-10-24 08:39 UTC, moroine commented on server/src/common/actions/effectifs.actions.ts
> +    });
Ce n'est pas bon, la `cle_ministere_educatif` identifie une offre de formation unique (organisme, rncp). Ici tu n'as pas l'information de la formation mais plutot de la certification (ce qui t'interresse c'est les intitule & l'opco.

Pour l'intitule le mieux c'est d'utiliser l'API alternance car on peut retourner toutes les informations d'une certification. Et dans ce cas pas besoin de computed

2024-10-24 08:39 UTC, moroine commented on server/src/common/actions/effectifs.actions.ts
> +    const rncpList = await opcosRncpDb().find({ "_computed.rncp.code": rncp }).toArray();
La liste des RNCP est-elle bien construite, que ce passe-t-il lorsque le rncp est echue ?

2024-10-24 08:39 UTC, moroine commented on server/src/jobs/hydrate/effectifs/hydrate-effectifs-computed.ts
> +  });
Les méthodes d'hydratation doivent mettre à jour TOUS les effectifs et de manière quotienne (QUID d'une formation qui change, le computed doit etre MAJ).

2024-10-24 08:39 UTC, moroine commented on server/src/jobs/hydrate/effectifs/hydrate-effectifs-computed.ts
> +    };
Logique dupliquée avec le fichier précédent

2024-10-28 07:52 UTC, Pomarom commented on server/src/common/actions/effectifs.actions.ts
> +    });
Pourtant il semble que la cme soit clé d'unicité : 
```sql
// sur formationCatalogue
[
  {
    $group:
      {
        _id: "$cle_ministere_educatif",
        count: {
          $sum: 1
        }
      }
  },
  {
    $match:
      {
        count: {
          $gt: 1
        }
      }
  }
] // => Pas de résultat
```
C'est pas suffisant de se baser sur la cme ?

2024-10-28 07:54 UTC, Pomarom commented on server/src/jobs/hydrate/effectifs/hydrate-effectifs-computed.ts
> +  });
Ouais mais le cfd et/ou rncp n'est pas obligatoire dans la transmission d'effectif. Comment calculer le computed si on a pas des infos de la formation ?

2024-10-28 07:58 UTC, Pomarom commented on server/src/common/actions/effectifs.actions.ts
> +    const rncpList = await opcosRncpDb().find({ "_computed.rncp.code": rncp }).toArray();
Pour un RNCP qui n'est plus dans sa date de validité, on a quand même besoin de calculer son computed, quitte à mettre un boolean ( valid: false ou autre ) dans le computed .
Mais on a pas encore statué sur l'affichage d'un effectif dont la formation n'est plus valide

2025-09-09 10:04 UTC, closed without merging