Add pre-commit hook
mission-apprentissage/flux-retour-cfas pull request #61
Opened 2020-10-30 17:19 UTC by stephane-ruhlmann

2020-10-30 20:46 UTC, stephane-ruhlmann commented
> Tu pourrais meme faire une PR sur le template (modèle qu'on utilise pour toutes les apps de la mission ;)

Here we go https://github.com/mission-apprentissage/template-apprentissage/pull/11

2020-11-03 14:29 UTC, sbenfares requested changes

2020-11-03 14:29 UTC, sbenfares commented on server/package.json
> +    "lint-staged": ">=10",
Coté back on essaie de fix les dependancies

2020-11-03 14:38 UTC, stephane-ruhlmann commented on server/package.json
> +    "lint-staged": ">=10",
Ok, dans ce cas je peux modifier la conf `.yarnrc` pour que ce soit fait automatiquement lorsqu'on ajoute une dep ?

2020-11-03 14:45 UTC, stephane-ruhlmann commented on server/package.json
> +    "lint-staged": ">=10",
Done ✅

2020-11-03 15:18 UTC, sbenfares approved these changes

2020-11-03 15:23 UTC, merged